// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDX2f55f37RgSeVbJNb8CdqQJTE2Iuihk',
    appId: '1:390102693113:web:00c15237d2b95fa6dade28',
    messagingSenderId: '390102693113',
    projectId: 'my-first-project-37725',
    authDomain: 'my-first-project-37725.firebaseapp.com',
    storageBucket: 'my-first-project-37725.firebasestorage.app',
    measurementId: 'G-NVDHNGT31J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn7w3uaorywnk1_kq96Xnn1P_f88Luxi4',
    appId: '1:390102693113:android:0c37346c1b9a25f8dade28',
    messagingSenderId: '390102693113',
    projectId: 'my-first-project-37725',
    storageBucket: 'my-first-project-37725.firebasestorage.app',
  );
}
